export * as AudienceController from './audienceController';
export * as AuthenticationController from './authenticationController';
export * as CampaignCandidateController from './campaignCandidateController';
export * as CampaignQuestionController from './campaignQuestionController';
export * as CategoryController from './categoryController';
export * as ChatController from './chatController';
export * as LiffController from './liffController';
export * as LineController from './lineController';
export * as ManagerController from './managerController';
export * as MemberController from './memberController';
export * as OccasionController from './occasionController';
export * as OccurrenceController from './occurrenceController';
export * as RegistrationController from './registrationController';
export * as RichmenuController from './richmenuController';
export * as SystemSettingController from './systemController';
export * as TemplateController from './templateController';
export * as SpectatorController from './spectatorController';
export * as CustomerRegistrationController from './customerRegistrationController';
export * as CampaignController from './campaignController';
export * as GiftController from './giftController';
export * as surveyController from './surveyController';
export * as surveyTemplateController from './surveyTemplateController';
export * as surveyRecordController from './surveyRecordController';
export * from './customer.controller';
export * from './lottery.controller';
export * from './coupon.controller';
export * as PrizeController from './prize.controller';
